name: "Test ESP-IDF Projects"
description: "Test ESP-IDF projects"

inputs:
  nodes:
    description: "The pytest nodes to test"
    required: true
  additional_args:
    description: "additional arguments to pass to pytest"
  junit_filepath:
    description: "The name of the junit file report"
  debug:
    description: "Enable debug mode"
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      shell: bash
      run: |
        pip install -U idf-ci
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Display structure of downloaded files
      shell: bash
      run: ls -R
    - name: Test ESP-IDF Projects
      shell: bash
      run: |
        args=()
        if [ -n "${{ inputs.additional_args }}" ]; then
          args+=("${{ inputs.additional_args }}")
        fi
        if [ -n "${{ inputs.junit_filepath }}" ]; then
          args+=("--junitxml=${{ inputs.junit_filepath }}")
        fi
        if [ "${{ inputs.debug }}" == "true" ]; then
          args+=("--log-cli-level=DEBUG")
        fi
        pytest ${{ inputs.nodes }} "${args[@]}"
    - name: Uplaod Test Results
      uses: actions/upload-artifact@v4
      with:
        path: ${{ inputs.junit_filepath }}
        name: test-report-${{ inputs.junit_filepath }}
