name: "Test ESP-IDF Projects"
description: "Test ESP-IDF projects"

inputs:
  nodes:
    description: "The pytest nodes to test"
    required: true
  additional_args:
    description: "additional arguments to pass to pytest"
  junit_filepath:
    description: "The name of the junit file report"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      shell: bash
      run: |
        pip install -U idf-ci
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Test ESP-IDF Projects
      shell: bash
      run: |
        if [ -z "${{ inputs.junit_filepath }}" ]; then
          pytest ${{ inputs.nodes }} ${{ inputs.additional_args }}
        else
          pytest ${{ inputs.nodes }} ${{ inputs.additional_args }} --junitxml=${{ inputs.junit_filename }}
        fi
    - name: Uplaod Test Results
      uses: actions/upload-artifact@v4
      with:
        path: ${{ inputs.junit_filepath }}
        name: test-report-${{ inputs.junit_filepath }}
